/* Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define CFC_NEED_BASE_STRUCT_DEF
#include "CFCBase.h"
#include "CFCParser.h"
#include "CFCParcel.h"
#include "CFCUtil.h"
#include "CFCLexHeader.h"
#include "CFCParseHeader.h"

#ifndef true
  #define true 1
  #define false 0
#endif

/* Routines generated by Lemon. */
void*
CFCParseHeaderAlloc(void * (*allocate)(size_t));
void
CFCParseHeader(void *header_parser, int token_type, CFCBase *value,
               CFCParserState *state);
void
CFCParseHeaderFree(void *header_parser, void(*freemem)(void*));
void
CFCParseHeaderTrace(FILE *trace, char *line_prefix);

struct CFCParser {
    CFCBase base;
    void *header_parser;
};

CFCParser*
CFCParser_new(void) {
    CFCParser *self = (CFCParser*)CFCBase_allocate(sizeof(CFCParser),
                                                   "Clownfish::Parser");
    return CFCParser_init(self);
}

CFCParser*
CFCParser_init(CFCParser *self) {
    self->header_parser = CFCParseHeaderAlloc(malloc);
    if (self->header_parser == NULL) {
        CFCUtil_die("Failed to allocate header parser");
    }
    return self;
}

void
CFCParser_destroy(CFCParser *self) {
    CFCParseHeaderFree(self->header_parser, free);
    CFCBase_destroy((CFCBase*)self);
}

static CFCParserState state;
CFCParserState *CFCParser_current_state  = &state;
void           *CFCParser_current_parser = NULL;
CFCParcel      *CFCParser_current_parcel = NULL;

CFCBase*
CFCParser_parse(CFCParser *self, const char *string) {
    CFCParser_current_parser = self->header_parser;
    state.result = NULL;
    state.errors = false;
    state.text   = NULL;

    YY_BUFFER_STATE buffer = yy_scan_bytes(string, (int)strlen(string));
    yylex();
    yy_delete_buffer(buffer);

    // Finish up.
    CFCParseHeader(CFCParser_current_parser, 0, NULL, &state);
    if (state.errors) {
        CFCBase_decref((CFCBase*)state.result);
        return NULL;
    }
    return state.result;
}

void
CFCParser_set_result(CFCParserState *self, CFCBase *result)
{
    CFCBase_decref(self->result);
    self->result = CFCBase_incref(result);
}

void
CFCParser_set_text(CFCParserState *self, const char *text, size_t len) {
    if (text) {
        if (len >= self->cap) {
            self->cap = len + 1;
            self->text = REALLOCATE(self->text, self->cap);
        }
        memcpy(self->text, text, len);
        self->text[len] = '\0';
    }
    else {
        FREEMEM(self->text);
        self->cap = 0;
        self->text = NULL;
    }
}

const char*
CFCParser_get_text(CFCParserState *self) {
    return self->text;
}

void
CFCParser_set_parcel(CFCParcel *parcel) {
    CFCBase_incref((CFCBase*)parcel);
    CFCBase_decref((CFCBase*)CFCParser_current_parcel);
    CFCParser_current_parcel = parcel;
}

CFCParcel*
CFCParser_get_parcel(void) {
    return CFCParser_current_parcel;
}

void
CFCParser_set_class_name(CFCParserState *state, const char *class_name) {
    FREEMEM(state->class_name);
    if (class_name) {
        state->class_name = CFCUtil_strdup(class_name);
    }
    else {
        state->class_name = NULL;
    }
}

const char*
CFCParser_get_class_name(CFCParserState *state) {
    return state->class_name;
}

void
CFCParser_set_class_cnick(CFCParserState *state, const char *class_cnick) {
    FREEMEM(state->class_cnick);
    if (class_cnick) {
        state->class_cnick = CFCUtil_strdup(class_cnick);
    }
    else {
        state->class_cnick = NULL;
    }
}

const char*
CFCParser_get_class_cnick(CFCParserState *state) {
    return state->class_cnick;
}

